apiVersion: v1
kind: Pod
metadata:
  name: chad-pod
spec:
  containers:
    - image: quay.io/navdeep_sachdeva/custom_httpd:1.0
      name: web
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443

    - image: docker.io/library/mysql
      name: db
      ports:
        - containerPort: 3306 
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: redhat-cm
              key: user
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: redhat-cm
              key: database

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redhat-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redhat-secret
              key: root_password
