---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gm-app
  namespace: project1
spec:
  ## Replicaset 
  replicas: 2
  selector:
    matchLabels:
      me: myself

  ## Pod Format/Template with some Containers
  template:
    metadata:
      name: matt-pod
      labels:
        me: myself
    spec:
      containers:
        - image: quay.io/navdeep_sachdeva/custom_httpd:1.0
          name: web
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443

        - image: docker.io/library/mysql
          name: db
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_USER
              value: kelly
            - name: MYSQL_DATABASE
              value: gm
            - name: MYSQL_PASSWORD
              value: mypa55
            - name: MYSQL_ROOT_PASSWORD
              value: r00tpa55

---
apiVersion: v1
kind: Service
metadata:
  name: gm-app
spec:
  ports:
    - name: first
      port: 8080
      targetPort: 8080
    - name: second
      port: 8443
      targetPort: 8443
  selector:
    me: myself

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gm-route

spec:
  to:
    kind: Service
    name: gm-app
