apiVersion: v1
kind: Pod
metadata:
  name: victor-pod
spec:
  restartPolicy: Never
  containers:
    - image: quay.io/navdeep_sachdeva/custom_httpd:1.0
      name: web
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443

    - image: docker.io/library/mysql
      name: db
      ports:
        - containerPort: 3306 
      # env:
      #   - name: MYSQL_USER
      #     value: kelly
      #   - name: MYSQL_DATABASE
      #     value: gm
      #   - name: MYSQL_PASSWORD
      #     value: mypa55
      #   - name: MYSQL_ROOT_PASSWORD
      #     value: r00tpa55
