---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  nfs:
    path: /exports-ocp4/data
    server: 192.168.50.254

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 9Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: somepod
spec:
  containers:
  - name: web
    image: quay.io/navdeep_sachdeva/custom_httpd:1.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /var/www/html
      name: robert-storage
  volumes:
  - name: robert-storage
    persistentVolumeClaim:
      claimName: app-pvc
