apiVersion: v1
kind: Pod
metadata:
  name: matt-pod
spec:
  containers:
    - image: quay.io/navdeep_sachdeva/custom_httpd:1.0
      name: web
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443

# status:
